# Generated by Django 2.0.3 on 2018-04-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pak_Political_Trends', '0002_auto_20180407_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendsform',
            name='topic',
            field=models.CharField(help_text='HELLO', max_length=100),
        ),
    ]
